[package]
name = "filecmp"
version = "0.0.2"
authors = ["owtotwo <owtotwo@163.com>"]
license = "LGPL-3.0-only"
description = "(Work-In-Progress) Utilities for comparing files and directories, the rust implementation for CPython filecmp module."
edition = "2018"

[dependencies]
